---
version: "2.1"
name: "duplicati"
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=0
      - PGID=0
      - TZ=India/kolkata
      - CLI_ARGS= #optional
    volumes:
      - ${DUPLICATI_DIR}/config>:/config
#      - </path/to/backups>:/backups
      - ${DUPLICATI_BACKUP_DIR}:/source
    ports:
      - 8200:8200
    restart: unless-stopped
    
networks:
    default:
        name: "intranet"
        external: true
