version: '3' 
services: 
    filebrowser:
        image: ${FB_IMAGE}
        container_name: filebrowser
        volumes:
            - ${FB_ROOT_DIR}:/srv
            #- ${FB_CONFIG_DIR}/filebrowser.db:/database.db
            #- ${FB_CONFIG_DIR}/filebrowser.json:/.filebrowser.json
            
#        ports:
#            - ${FB_WEBUI_PORT}:80

networks:
    default:
        name: "intranet"
