version: '3'
name: "nginx-proxy-manager"
services:
  app:
    image: 'jlesage/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:8080'
      - '81:8181'
      - '443:4443'
    volumes:
      - ${NGINX_PROXY_MANAGER_DIR}/2:/config
      
networks:
    default:
        name: "intranet"
