version: "2.1"
name: syncthing
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    hostname: syncthing #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ${SYNCTHING_CONFIG}:/config
      - ${SYNCTHING_DATA1}:/data1
      - ${SYNCTHING_DATA2}:/data2
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
