version: '3'
name: "watchtower"
services:
  watchtower:
    image: containrrr/watchtower
#    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#      - /etc/timezone:/etc/timezone:ro
    environment:
      - WATCHTOWER_RUN_ONCE=true
 #     - WATCHTOWER_CLEANUP=true
 #     - WATCHTOWER_LABEL_ENABLE=false
 #     - WATCHTOWER_INCLUDE_RESTARTING=true
      
#    labels:
#      - "com.centurylinklabs.watchtower.enable=true"
